version: '2'

services:

  app:
    image: eaudeweb/mac-logging:0.4.3
    env_file:
    - ./docker/app.env
    - ./docker/postgres.env
    volumes:
    - data:/var/local/pontaj/files

  cronjobs:
    image: eaudeweb/mac-logging:0.4.3
    entrypoint: ["./cronjobs-entrypoint.sh"]
    volumes:
    - data:/var/local/pontaj/files

  postgres:
    image: postgres:9-alpine
    container_name: pontaj.db
    env_file:
    - ./docker/postgres.env
    volumes:
    - data:/var/local/pontaj/postgresql

volumes:
  data:
    driver: local
