version: '2'

services:

  app:
    image: eaudeweb/mac-logging:2.0
    container_name: pontaj.app
    ports:
    - "5000:5000"
    volumes:
    - data:/var/local/pontaj/files

  cronjobs:
    image: eaudeweb/mac-logging:2.0
    container_name: pontaj.cronjobs
    volumes:
    - data:/var/local/pontaj/files
    entrypoint: ["./cronjobs-entrypoint.sh"]

volumes:
  data:
    driver: local
