version: '2'

services:

  app:
    image: eaudeweb/mac-logging:2.4
    env_file:
    - ./docker/app.env
    volumes:
    - data:/var/local/pontaj/files

  cronjobs:
    image: eaudeweb/mac-logging:2.4
    entrypoint: ["./cronjobs-entrypoint.sh"]
    volumes:
    - data:/var/local/pontaj/files

volumes:
  data:
    driver: local
