"""add_departament

Revision ID: 0ebf504d1381
Revises: 2ec956be90dc
Create Date: 2018-06-12 14:55:34.876845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebf504d1381'
down_revision = '2ec956be90dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'person', sa.Column('dept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'departament', ['dept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column(u'person', 'dept_id')
    op.drop_table('departament')
    # ### end Alembic commands ###
