"""add_comment_field

Revision ID: 2ec956be90dc
Revises: 48817d6da5b5
Create Date: 2018-06-12 12:12:50.999695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec956be90dc'
down_revision = '48817d6da5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'comment')
    # ### end Alembic commands ###
