"""add_exittime

Revision ID: 48817d6da5b5
Revises: 1a5642bba8f0
Create Date: 2018-06-05 15:10:00.743897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48817d6da5b5'
down_revision = '1a5642bba8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('exittime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'exittime')
    # ### end Alembic commands ###
